### ISSUE TITLE
can tc works with tpa?

### ISSUE THREAD

**Issue by johndb2016** [bytedance/libtpa#12]
we usually use tc to emulate network abnormal cases, since libtpa is a userspace tcp stack, so tc can't work with it ?

**Comment by yuanhanliu** [comment]
Yes, it won't work. However, Libtpa ships pktfuzz (located at src/pktfuzz), which can be used to simulate some very basic abnormal cases. Note that it might not work perfectly (it may have bugs), as we seldom run it. We don't really rely on it for the stableness. Instead, we use unit test to simulate all the abnormal inputs we think of.
