### ISSUE TITLE
is Intel platform supported?

### ISSUE THREAD

**Issue by johndb2016** [bytedance/libtpa#3]

**Comment by yuanhanliu** [comment]
Do you mean Intel NICs? Yes, currently only Intel E810 is supported. Check [here](https://github.com/bytedance/libtpa/blob/next/doc/nics/e810.rst) for more information.

Note that the code is currently hosted at the next branch.

**Comment by johndb2016** [comment]
nop, i mean cpu, and AMD64&ARM are found in the user guide, so i wonder whether intel cpu supported

**Comment by yuanhanliu** [comment]
I see. Here AMD64 means the [x86-64 CPU arch](https://en.wikipedia.org/wiki/X86-64), including Intel CPUs.
