### ISSUE TITLE
Scope of Application Inquiry

### ISSUE THREAD

**Issue by Clownier** [bytedance/libtpa#6]
I noticed that this code repository is being used internally by your company and provides usage examples related to Redis. However, I couldn't find any relevant descriptions on your company's official website; I only found records about "Tarzan." I'd like to inquire about significant deployment instances of this project, such as file storage or block storage. Additionally, could you clarify the relationship between Libtpa and Tarzan?

**Comment by yuanhanliu** [comment]
Libtpa is Tarzan. However, Tarzan is a registered trademark that we can not use it. Hence it's renamed to Libtpa. Currently, the major usage of Libtpa (or Tarzan) at Bytedance is block storage.
